version: "3"
services:
  booktr:
    image: aceberg/booktr   
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/BookTr:/data/BookTr
    environment:
      TZ: Asia/Novosibirsk    # required, default: ""
      HOST: "0.0.0.0"         # optional, default: 0.0.0.0
      PORT: "8830"            # optional, default: 8830
      THEME: "simplex"        # optional, default: simplex
      COLOR: "dark"           # optional, default: dark